### PR TITLE
Frontend

### PR DESCRIPTION
**Pull request by Ayleinee**
Vue js frontend added
- new design + images
- responsiveness on mobile and desktop
- animations
- map is merged into the front end

### CODE REVIEW

**Comment by Quantumplation** [comment]
@Ayleinee Thanks for the PR!

Unfortunately, there are some compilation errors.
```
-  Building for production...
00:39:56.205  
[BABEL] Note: The code generator has deoptimised the styling of /vercel/41b1ae4a/src/components/Map/muy_map_conf.js as it exceeds the max of 500KB.
00:40:06.804  
 ERROR  Failed to compile with 1 errors4:40:06 AM
00:40:06.805  
 error  in ./src/components/Map/muy_map_conf.js
00:40:06.805  
Module Error (from ./node_modules/eslint-loader/index.js):
00:40:06.805  
/vercel/41b1ae4a/src/components/Map/muy_map_conf.js
00:40:06.805  
  15:17  error  'google' is not defined                             no-undef
00:40:06.805  
  26:24  error  'google' is not defined                             no-undef
00:40:06.805  
  37:28  error  'google' is not defined                             no-undef
00:40:06.805  
  55:7   error  'markerCluster' is assigned a value but never used  no-unused-vars
00:40:06.805  
  55:27  error  'MarkerClusterer' is not defined                    no-undef
00:40:06.805  
✖ 5 problems (5 errors, 0 warnings)
```

**Comment by Quantumplation** [comment]
Wow! This is fantastic, thank you for all that work.

Some comments:
- it's no longer asking for my location and centering the map
- in the current develop branch, after the first time you dismiss the description, it starts you directly on the map, to encourage repeated use
- by having the map something you scroll down to, the controls on PC and mobile get slightly more awkward: on PC you can't scroll to zoom, because it doesn't know if you're trying to scroll up or not, and on mobile you have to use two fingers to pan around

Some of these may not have solutions anymore, but if there's something you can think of to address that, it'd be super helpful.

Otherwise, as long as we fix the location thing I'm good to merge this.

This kind of makes me feel like I HAVE to follow through and establish a non-profit now lol...

**Comment by SupernaviX** [comment]
damn

**Comment by Quantumplation** [comment]
I haven't forgotten about this.  I'm working on forming a non-profit right now to shield myself a bit from angry people, and once I do that, I'll merge this and we can launch the site.

@Ayleinee I'm probably going to draft something up to have people who contribute, granting the nonprofit an indefinite and unrestricted license to use all assets submitted this way;  Do you have any objections to something like that? (Exact wording pending)

**Comment by Ayleinee** [comment]
Nope, no objections.

**Pull request merged**
